using Backend.Data;
using Backend.DTOs;
using Backend.Models;
using Microsoft.EntityFrameworkCore;

namespace Backend.Services;

public class WeeklyMealPlanService
{
    private static readonly string[] Slots = ["breakfast", "lunch", "dinner"];
    private const string AutoWeeklyMarker = "[AUTO_WEEKLY]";

    private readonly AppDbContext _db;
    private readonly GeminiService _gemini;
    private readonly NotificationService _notificationService;

    public WeeklyMealPlanService(
        AppDbContext db,
        GeminiService gemini,
        NotificationService notificationService)
    {
        _db = db;
        _gemini = gemini;
        _notificationService = notificationService;
    }

    public async Task<WeeklyPlanEnsureResponse> EnsureCurrentWeekAsync(
        Guid userId,
        WeeklyPlanEnsureRequest request,
        CancellationToken ct)
    {
        var todayUtc = DateTime.UtcNow.Date;
        var weekStart = StartOfWeek(todayUtc);
        var weekEndExclusive = weekStart.AddDays(7);

        var existing = await _db.MealPlans
            .Where(x => x.UserId == userId)
            .Where(x => x.Date >= weekStart && x.Date < weekEndExclusive)
            .ToListAsync(ct);

        var replacedAutoCount = 0;
        if (request.RegenerateAutoSlots)
        {
            var autoEntries = existing.Where(IsAutoWeekly).ToList();
            replacedAutoCount = autoEntries.Count;
            if (autoEntries.Count > 0)
            {
                _db.MealPlans.RemoveRange(autoEntries);
                await _db.SaveChangesAsync(ct);
                existing = existing.Except(autoEntries).ToList();
            }
        }

        var existingSlots = new HashSet<string>(
            existing.Select(ToSlotKey),
            StringComparer.OrdinalIgnoreCase);

        var missingSlots = BuildMissingSlots(weekStart, existingSlots);
        if (missingSlots.Count == 0)
        {
            return new WeeklyPlanEnsureResponse
            {
                WeekStart = weekStart,
                WeekEnd = weekEndExclusive.AddDays(-1),
                CreatedCount = 0,
                ReplacedAutoCount = replacedAutoCount,
                AlreadyPlanned = true,
                HasAutoGeneratedThisWeek = existing.Any(IsAutoWeekly),
            };
        }

        var pantryIngredients = await _db.Ingredients
            .AsNoTracking()
            .Where(x => x.UserId == userId)
            .Where(x => x.Quantity > 0)
            .Where(x => x.ExpiredAt == null || x.ExpiredAt >= todayUtc)
            .Select(x => new GeminiIngredient
            {
                Name = x.Name,
                Quantity = x.Quantity,
                Unit = x.Unit
            })
            .ToListAsync(ct);

        var recentCooked = await _db.CookingHistories
            .AsNoTracking()
            .Where(x => x.UserId == userId && x.CookedAt >= DateTime.UtcNow.AddDays(-14))
            .Select(x => x.RecipeName)
            .ToListAsync(ct);

        recentCooked.AddRange(existing.Select(x => x.RecipeName));

        var aiNeeded = Math.Max(missingSlots.Count, 7);
        var aiRecipes = await _gemini.GenerateRecipesAsync(
            pantryIngredients,
            recentCooked,
            aiNeeded,
            "mixed",
            ct);

        var candidates = aiRecipes
            .Select(x => (x.Name ?? string.Empty).Trim())
            .Where(x => !string.IsNullOrWhiteSpace(x))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();

        var created = 0;
        var nextFallback = 0;
        foreach (var slot in missingSlots)
        {
            var recipeName = PickRecipeName(candidates, slot.MealType, ref nextFallback);
            var entity = new MealPlan
            {
                UserId = userId,
                Date = slot.Date,
                MealType = slot.MealType,
                RecipeName = recipeName,
                Servings = 1,
                Note = BuildAutoNote(request.NutritionGoal, request.WeeklyBudget)
            };

            _db.MealPlans.Add(entity);
            created++;
        }

        if (created > 0)
        {
            await _db.SaveChangesAsync(ct);
            await _notificationService.CreateNotificationAsync(
                userId,
                "Đã tạo kế hoạch tuần",
                $"Đã tạo tự động {created} bữa ăn cho tuần này."
            );
        }

        return new WeeklyPlanEnsureResponse
        {
            WeekStart = weekStart,
            WeekEnd = weekEndExclusive.AddDays(-1),
            CreatedCount = created,
            ReplacedAutoCount = replacedAutoCount,
            AlreadyPlanned = false,
            HasAutoGeneratedThisWeek = created > 0 || existing.Any(IsAutoWeekly),
        };
    }

    private static string BuildAutoNote(string? nutritionGoal, decimal? weeklyBudget)
    {
        var goal = (nutritionGoal ?? string.Empty).Trim();
        if (string.IsNullOrWhiteSpace(goal) && weeklyBudget == null)
        {
            return AutoWeeklyMarker;
        }

        var budgetPart = weeklyBudget.HasValue ? $"|BUDGET:{weeklyBudget.Value:0.##}" : string.Empty;
        var goalPart = !string.IsNullOrWhiteSpace(goal) ? $"|GOAL:{goal}" : string.Empty;
        return $"{AutoWeeklyMarker}{goalPart}{budgetPart}";
    }

    private static DateTime StartOfWeek(DateTime date)
    {
        var diff = (int)date.DayOfWeek - (int)DayOfWeek.Monday;
        if (diff < 0) diff += 7;
        return date.AddDays(-diff);
    }

    private static List<MissingSlot> BuildMissingSlots(DateTime weekStart, HashSet<string> existing)
    {
        var missing = new List<MissingSlot>();
        for (var day = 0; day < 7; day++)
        {
            var date = weekStart.AddDays(day);
            foreach (var mealType in Slots)
            {
                var key = BuildSlotKey(date, mealType);
                if (!existing.Contains(key))
                {
                    missing.Add(new MissingSlot(date, mealType));
                }
            }
        }

        return missing;
    }

    private static string PickRecipeName(List<string> candidates, string mealType, ref int fallbackIndex)
    {
        if (candidates.Count > 0)
        {
            var picked = candidates[0];
            candidates.RemoveAt(0);
            return picked;
        }

        var fallback = mealType switch
        {
            "breakfast" => "Bánh mì trứng",
            "lunch" => "Cơm gà",
            "dinner" => "Canh rau thịt băm",
            _ => "Món gợi ý"
        };

        fallbackIndex++;
        return fallbackIndex == 1 ? fallback : $"{fallback} {fallbackIndex}";
    }

    private static string ToSlotKey(MealPlan mealPlan)
    {
        return BuildSlotKey(mealPlan.Date.Date, mealPlan.MealType);
    }

    public static bool IsAutoWeekly(MealPlan mealPlan)
    {
        return IsAutoWeeklyNote(mealPlan.Note);
    }

    public static bool IsAutoWeeklyNote(string? note)
    {
        return !string.IsNullOrWhiteSpace(note)
            && note.Contains(AutoWeeklyMarker, StringComparison.OrdinalIgnoreCase);
    }

    private static string BuildSlotKey(DateTime date, string mealType)
    {
        return $"{date:yyyy-MM-dd}:{mealType.Trim().ToLowerInvariant()}";
    }

    private sealed record MissingSlot(DateTime Date, string MealType);
}
