using System.ComponentModel.DataAnnotations;

namespace Backend.DTOs;

public class MealPlanCreateRequest
{
    [Required]
    public DateTime Date { get; set; }

    [Required, MaxLength(20)]
    public string MealType { get; set; } = "";

    [Required, MaxLength(150)]
    public string RecipeName { get; set; } = "";

    public int Servings { get; set; } = 1;

    [MaxLength(200)]
    public string? Note { get; set; }
}

public class MealPlanUpdateRequest
{
    [Required]
    public DateTime Date { get; set; }

    [Required, MaxLength(20)]
    public string MealType { get; set; } = "";

    [Required, MaxLength(150)]
    public string RecipeName { get; set; } = "";

    public int Servings { get; set; } = 1;

    [MaxLength(200)]
    public string? Note { get; set; }
}

public class MealPlanResponse
{
    public Guid Id { get; set; }
    public DateTime Date { get; set; }
    public string MealType { get; set; } = "";
    public string RecipeName { get; set; } = "";
    public int Servings { get; set; }
    public string? Note { get; set; }
    public bool IsAutoGenerated { get; set; }
}

public class WeeklyPlanEnsureRequest
{
    public decimal? WeeklyBudget { get; set; }
    public string? NutritionGoal { get; set; }
    public bool RegenerateAutoSlots { get; set; }
}

public class WeeklyPlanEnsureResponse
{
    public DateTime WeekStart { get; set; }
    public DateTime WeekEnd { get; set; }
    public int CreatedCount { get; set; }
    public int ReplacedAutoCount { get; set; }
    public bool AlreadyPlanned { get; set; }
    public bool HasAutoGeneratedThisWeek { get; set; }
}

public class WeeklyPlannerIngredientsResponse
{
    public DateTime WeekStart { get; set; }
    public DateTime WeekEnd { get; set; }
    public List<DailyPlannerIngredientsResponse> Days { get; set; } = new();
}

public class DailyPlannerIngredientsResponse
{
    public DateTime Date { get; set; }
    public List<PlannerIngredientAggregateDto> Ingredients { get; set; } = new();
}

public class PlannerIngredientAggregateDto
{
    public string Name { get; set; } = "";
    public double Quantity { get; set; }
    public string Unit { get; set; } = "";
}
