import 'dart:convert';
import 'package:flutter/material.dart';
import '../../../core/api/api_client.dart';
import '../../../core/utils/pantry_scope.dart';
import '../../shopping/shopping_service.dart';
import '../../shopping/shopping_list_model.dart';

enum PlannerShoppingMode { daily, weeklyMerged }

class PlannerShoppingGenerationResult {
	final PlannerShoppingMode mode;
	final int sourcePlanCount;
	final int createdListCount;
	final int createdItemCount;
	final String? firstCreatedListId;

	const PlannerShoppingGenerationResult({
		required this.mode,
		required this.sourcePlanCount,
		required this.createdListCount,
		required this.createdItemCount,
		this.firstCreatedListId,
	});
}

class _PlannerDailyIngredients {
	final DateTime date;
	final List<_PlannerIngredientRow> ingredients;

	const _PlannerDailyIngredients({
		required this.date,
		required this.ingredients,
	});
}

class _PlannerIngredientRow {
	final String name;
	final double quantity;
	final String unit;

	const _PlannerIngredientRow({
		required this.name,
		required this.quantity,
		required this.unit,
	});
}

enum MealType { breakfast, lunch, dinner, snack }

extension MealTypeX on MealType {
	String get label {
		switch (this) {
			case MealType.breakfast:
				return 'Bữa sáng';
			case MealType.lunch:
				return 'Bữa trưa';
			case MealType.dinner:
				return 'Bữa tối';
			case MealType.snack:
				return 'Bữa phụ';
		}
	}

	IconData get icon {
		switch (this) {
			case MealType.breakfast:
				return Icons.free_breakfast;
			case MealType.lunch:
				return Icons.lunch_dining;
			case MealType.dinner:
				return Icons.dinner_dining;
			case MealType.snack:
				return Icons.cookie;
		}
	}

	String get apiValue => name;

	static MealType fromApi(String value) {
		switch (value.toLowerCase()) {
			case 'breakfast':
				return MealType.breakfast;
			case 'lunch':
				return MealType.lunch;
			case 'dinner':
				return MealType.dinner;
			case 'snack':
				return MealType.snack;
			default:
				return MealType.lunch;
		}
	}
}

class MealPlanEntry {
	final String id;
	final DateTime date;
	final MealType mealType;
	final String recipeName;
	final int servings;
	final String? note;
	final bool isAutoGenerated;

	const MealPlanEntry({
		required this.id,
		required this.date,
		required this.mealType,
		required this.recipeName,
		required this.servings,
		this.note,
		this.isAutoGenerated = false,
	});

	MealPlanEntry copyWith({
		DateTime? date,
		MealType? mealType,
		String? recipeName,
		int? servings,
		String? note,
		bool? isAutoGenerated,
	}) {
		return MealPlanEntry(
			id: id,
			date: date ?? this.date,
			mealType: mealType ?? this.mealType,
			recipeName: recipeName ?? this.recipeName,
			servings: servings ?? this.servings,
			note: note ?? this.note,
			isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
		);
	}
}

class WeeklyPlanStatus {
	final DateTime weekStart;
	final DateTime weekEnd;
	final int createdCount;
	final int replacedAutoCount;
	final bool alreadyPlanned;
	final bool hasAutoGeneratedThisWeek;

	const WeeklyPlanStatus({
		required this.weekStart,
		required this.weekEnd,
		required this.createdCount,
		required this.replacedAutoCount,
		required this.alreadyPlanned,
		required this.hasAutoGeneratedThisWeek,
	});
}

class PlannerService extends ChangeNotifier {
	static final PlannerService instance = PlannerService._();

	PlannerService._();

	final List<MealPlanEntry> _entries = [];
	WeeklyPlanStatus? _weeklyStatus;

	List<MealPlanEntry> get entries => List.unmodifiable(_entries);
	WeeklyPlanStatus? get weeklyStatus => _weeklyStatus;

	bool _loading = false;
	bool get isLoading => _loading;

	DateTime normalizeDate(DateTime date) {
		return DateTime(date.year, date.month, date.day);
	}

	DateTime weekStartFor(DateTime date) {
		final normalized = normalizeDate(date);
		return normalized.subtract(Duration(days: normalized.weekday - 1));
	}

	List<DateTime> daysOfWeek(DateTime weekStart) {
		return List.generate(7, (index) => weekStart.add(Duration(days: index)));
	}

	List<MealPlanEntry> entriesForDate(DateTime date) {
		final target = normalizeDate(date);
		final filtered = _entries.where((entry) {
			return normalizeDate(entry.date) == target;
		}).toList();
		filtered.sort((a, b) => a.mealType.index.compareTo(b.mealType.index));
		return filtered;
	}

	List<MealPlanEntry> entriesForWeek(DateTime weekStart) {
		final start = normalizeDate(weekStart);
		final end = start.add(const Duration(days: 6));
		final filtered = _entries.where((entry) {
			final date = normalizeDate(entry.date);
			return !date.isBefore(start) && !date.isAfter(end);
		}).toList();
		filtered.sort((a, b) => a.date.compareTo(b.date));
		return filtered;
	}

	Future<PlannerShoppingGenerationResult> generateShoppingListsForWeek({
		required DateTime weekStart,
		required PlannerShoppingMode mode,
		void Function(String message)? onProgress,
	}) async {
		onProgress?.call('Đang chuẩn bị dữ liệu...');
		await PantryScope.ensureInitialized();
		final today = normalizeDate(DateTime.now());
		final weekStartDate = normalizeDate(weekStart);
		final effectiveStart = today.isAfter(weekStartDate) ? today : weekStartDate;

		final weekEntries = entriesForWeek(weekStart)
			.where((entry) => !normalizeDate(entry.date).isBefore(effectiveStart))
			.toList();
		if (weekEntries.isEmpty) {
			return PlannerShoppingGenerationResult(
				mode: mode,
				sourcePlanCount: 0,
				createdListCount: 0,
				createdItemCount: 0,
				firstCreatedListId: null,
			);
		}

		final shoppingService = ShoppingService.instance;
		onProgress?.call('Đang đồng bộ danh sách mua sắm...');
		await shoppingService.loadLists();
		final existingLists = List<ShoppingListModel>.from(shoppingService.lists);
		onProgress?.call('Đang lấy nguyên liệu từ planner...');
		final dailyIngredients = await _loadWeeklyIngredients(weekStart);
		final ingredientDays = dailyIngredients
			.where((day) => !normalizeDate(day.date).isBefore(effectiveStart))
			.map(
				(day) => _PlannerDailyIngredients(
					date: day.date,
					ingredients: day.ingredients.where(_isShoppingIngredient).toList(),
				),
			)
			.where((day) => day.ingredients.isNotEmpty)
			.toList();
		if (ingredientDays.isEmpty) {
			return PlannerShoppingGenerationResult(
				mode: mode,
				sourcePlanCount: weekEntries.length,
				createdListCount: 0,
				createdItemCount: 0,
				firstCreatedListId: null,
			);
		}

		if (mode == PlannerShoppingMode.weeklyMerged) {
			final weekLabel = _formatWeekLabel(weekStartFor(weekStart));
			final weeklyListName = 'Đi chợ tuần $weekLabel';
			onProgress?.call('Đang tạo list gộp theo tuần...');
			await _deleteMatchedLists(
				shoppingService: shoppingService,
				lists: existingLists,
				matcher: (list) => list.name.trim().toLowerCase() == weeklyListName.toLowerCase(),
			);
			final list = await shoppingService.createList(
				name: weeklyListName,
				planDate: weekStartFor(weekStart),
			);
			if (list == null) {
				return PlannerShoppingGenerationResult(
					mode: mode,
					sourcePlanCount: weekEntries.length,
					createdListCount: 0,
					createdItemCount: 0,
					firstCreatedListId: null,
				);
			}

			var createdItems = 0;
			final merged = _mergeIngredients(ingredientDays);
			createdItems = await shoppingService.addManualItemsBatch(
				listId: list.id,
				items: merged.values
					.map(
						(item) => {
							'name': item.name,
							'quantity': item.quantity,
							'unit': item.unit,
						},
					)
					.toList(),
			);
			onProgress?.call('Đang hoàn tất dữ liệu shopping...');
			await shoppingService.loadLists();
			onProgress?.call('Đã xong');

			return PlannerShoppingGenerationResult(
				mode: mode,
				sourcePlanCount: weekEntries.length,
				createdListCount: 1,
				createdItemCount: createdItems,
				firstCreatedListId: list.id,
			);
		}

		var createdLists = 0;
		var createdItems = 0;
		String? firstCreatedListId;
		final sortedDays = ingredientDays.toList()..sort((a, b) => a.date.compareTo(b.date));
		var dayIndex = 0;
		for (final dayPlan in sortedDays) {
			dayIndex++;
			final day = normalizeDate(dayPlan.date);
			final dailyListName = 'Đi chợ ${_formatDate(day)}';
			onProgress?.call('Đang tạo list ngày $dayIndex/${sortedDays.length}...');
			await _deleteMatchedLists(
				shoppingService: shoppingService,
				lists: existingLists,
				matcher: (list) => _matchesDailyPlannerListName(list.name, day),
			);
			final list = await shoppingService.createList(
				name: dailyListName,
				planDate: day,
			);
			if (list == null) continue;

			firstCreatedListId ??= list.id;
			createdLists++;
			final mergedDailyIngredients = _mergeIngredientRows(dayPlan.ingredients);
			createdItems += await shoppingService.addManualItemsBatch(
				listId: list.id,
				items: mergedDailyIngredients
					.map(
						(item) => {
							'name': item.name,
							'quantity': item.quantity,
							'unit': item.unit,
						},
					)
					.toList(),
			);
		}

		onProgress?.call('Đang hoàn tất dữ liệu shopping...');
		await shoppingService.loadLists();
		onProgress?.call('Đã xong');

		return PlannerShoppingGenerationResult(
			mode: mode,
			sourcePlanCount: weekEntries.length,
			createdListCount: createdLists,
			createdItemCount: createdItems,
			firstCreatedListId: firstCreatedListId,
		);
	}

	void addEntry(MealPlanEntry entry) {
		_entries.add(entry);
		notifyListeners();
	}

	void updateEntry(MealPlanEntry entry) {
		final index = _entries.indexWhere((e) => e.id == entry.id);
		if (index == -1) return;
		_entries[index] = entry;
		notifyListeners();
	}

	void deleteEntry(String id) {
		_entries.removeWhere((entry) => entry.id == id);
		notifyListeners();
	}

	String createId() => DateTime.now().microsecondsSinceEpoch.toString();

	Future<void> loadWeek(DateTime weekStart) async {
		if (_loading) return;
		_loading = true;
		notifyListeners();
		try {
			final start = normalizeDate(weekStart);
			final end = start.add(const Duration(days: 6));
			final res = await ApiClient.get(
				'/planner',
				auth: true,
				queryParameters: {
					'from': start.toIso8601String(),
					'to': end.toIso8601String(),
				},
			);
			if (res.statusCode != 200) {
				throw Exception(_extractError(res));
			}
			final data = jsonDecode(res.body);
			final items = <MealPlanEntry>[];
			if (data is List) {
				for (final item in data) {
					if (item is Map<String, dynamic>) {
						items.add(_fromApi(item));
					}
				}
			}
			_entries
				..clear()
				..addAll(items);
			notifyListeners();
		} finally {
			_loading = false;
			notifyListeners();
		}
	}

	Future<WeeklyPlanStatus> ensureWeeklyPlan({
		double? weeklyBudget,
		String? nutritionGoal,
		bool regenerateAutoSlots = false,
	}) async {
		final body = <String, dynamic>{};
		if (weeklyBudget != null) {
			body['weeklyBudget'] = weeklyBudget;
		}
		if (nutritionGoal != null && nutritionGoal.trim().isNotEmpty) {
			body['nutritionGoal'] = nutritionGoal.trim();
		}
		if (regenerateAutoSlots) {
			body['regenerateAutoSlots'] = true;
		}

		final res = await ApiClient.post(
			'/planner/weekly/ensure',
			body,
			auth: true,
		);

		if (res.statusCode != 200) {
			throw Exception(_extractError(res));
		}

		final data = jsonDecode(res.body);
		if (data is! Map<String, dynamic>) {
			throw Exception('Phản hồi kế hoạch tuần không hợp lệ.');
		}

		final weekStartRaw = (data['weekStart'] ?? '').toString();
		final weekEndRaw = (data['weekEnd'] ?? '').toString();
		final status = WeeklyPlanStatus(
			weekStart: DateTime.tryParse(weekStartRaw) ?? DateTime.now(),
			weekEnd: DateTime.tryParse(weekEndRaw) ?? DateTime.now(),
			createdCount: _asInt(data['createdCount']),
			replacedAutoCount: _asInt(data['replacedAutoCount']),
			alreadyPlanned: data['alreadyPlanned'] == true,
			hasAutoGeneratedThisWeek: data['hasAutoGeneratedThisWeek'] == true,
		);

		_weeklyStatus = status;
		notifyListeners();
		return status;
	}

	Future<void> createPlan(MealPlanEntry entry) async {
		final res = await ApiClient.post(
			'/planner',
			{
				'date': normalizeDate(entry.date).toIso8601String(),
				'mealType': entry.mealType.apiValue,
				'recipeName': entry.recipeName,
				'servings': entry.servings,
				'note': entry.note,
			},
			auth: true,
		);
		if (res.statusCode != 201) {
			throw Exception(_extractError(res));
		}
		final data = jsonDecode(res.body);
		if (data is Map<String, dynamic>) {
			addEntry(_fromApi(data));
		}
	}

	Future<void> updatePlan(MealPlanEntry entry) async {
		final res = await ApiClient.put(
			'/planner/${entry.id}',
			{
				'date': normalizeDate(entry.date).toIso8601String(),
				'mealType': entry.mealType.apiValue,
				'recipeName': entry.recipeName,
				'servings': entry.servings,
				'note': entry.note,
			},
			auth: true,
		);
		if (res.statusCode != 200) {
			throw Exception(_extractError(res));
		}
		final data = jsonDecode(res.body);
		if (data is Map<String, dynamic>) {
			updateEntry(_fromApi(data));
		}
	}

	Future<void> removePlan(String id) async {
		final res = await ApiClient.delete(
			'/planner/$id',
			auth: true,
		);
		if (res.statusCode != 204) {
			throw Exception(_extractError(res));
		}
		deleteEntry(id);
	}

	MealPlanEntry _fromApi(Map<String, dynamic> item) {
		return MealPlanEntry(
			id: (item['id'] ?? '').toString(),
			date: DateTime.parse(item['date'] as String),
			mealType: MealTypeX.fromApi(item['mealType'] as String),
			recipeName: (item['recipeName'] ?? '').toString(),
			servings: item['servings'] is int
					? item['servings'] as int
					: int.tryParse(item['servings'].toString()) ?? 1,
			note: item['note']?.toString(),
			isAutoGenerated: item['isAutoGenerated'] == true,
		);
	}

	int _asInt(dynamic value) {
		if (value is int) return value;
		return int.tryParse(value?.toString() ?? '') ?? 0;
	}

	String _extractError(dynamic res) {
		try {
			if (res.statusCode == 401) {
				return 'Vui lòng đăng nhập lại.';
			}
			final data = jsonDecode(res.body);
			if (data is Map && data['message'] is String) {
				final message = (data['message'] as String).trim();
				if (message.isNotEmpty) return message;
			}
		} catch (_) {}
		switch (res.statusCode) {
			case 400:
				return 'Dữ liệu không hợp lệ.';
			case 404:
				return 'Không tìm thấy dữ liệu.';
			default:
				return 'Không thể xử lý yêu cầu.';
		}
	}

	Map<String, _PlannerIngredientRow> _mergeIngredients(List<_PlannerDailyIngredients> days) {
		final merged = <String, _PlannerIngredientRow>{};
		for (final day in days) {
			for (final ingredient in _mergeIngredientRows(day.ingredients)) {
				final key = '${ingredient.name.trim().toLowerCase()}|${ingredient.unit.trim().toLowerCase()}';
				final existing = merged[key];
				if (existing == null) {
					merged[key] = ingredient;
					continue;
				}
				merged[key] = _PlannerIngredientRow(
					name: existing.name,
					quantity: existing.quantity + ingredient.quantity,
					unit: existing.unit,
				);
			}
		}
		return merged;
	}

	List<_PlannerIngredientRow> _mergeIngredientRows(List<_PlannerIngredientRow> rows) {
		final merged = <String, _PlannerIngredientRow>{};
		for (final row in rows) {
			final key = '${row.name.trim().toLowerCase()}|${row.unit.trim().toLowerCase()}';
			final existing = merged[key];
			if (existing == null) {
				merged[key] = row;
				continue;
			}
			merged[key] = _PlannerIngredientRow(
				name: existing.name,
				quantity: existing.quantity + row.quantity,
				unit: existing.unit,
			);
		}
		return merged.values.toList()
			..sort((a, b) => a.name.toLowerCase().compareTo(b.name.toLowerCase()));
	}

	Future<void> _deleteMatchedLists({
		required ShoppingService shoppingService,
		required List<ShoppingListModel> lists,
		required bool Function(ShoppingListModel list) matcher,
	}) async {
		for (final list in lists.where(matcher)) {
			await shoppingService.deleteList(list.id);
		}
	}

	bool _matchesDailyPlannerListName(String listName, DateTime day) {
		final normalized = listName.trim().toLowerCase();
		final full = 'đi chợ ${_formatDate(day)}'.toLowerCase();
		final legacy = 'đi chợ ${_formatLegacyDate(day)}'.toLowerCase();
		return normalized == full || normalized == legacy;
	}

	bool _isShoppingIngredient(_PlannerIngredientRow ingredient) {
		return PantryScope.isPantryManagedIngredient(ingredient.name);
	}

	Future<List<_PlannerDailyIngredients>> _loadWeeklyIngredients(DateTime weekStart) async {
		final normalizedWeekStart = normalizeDate(weekStart);
		final res = await ApiClient.get(
			'/planner/weekly/ingredients',
			auth: true,
			queryParameters: {'weekStart': normalizedWeekStart.toIso8601String()},
		);
		if (res.statusCode != 200) {
			throw Exception(_extractError(res));
		}

		final data = jsonDecode(res.body);
		if (data is! Map<String, dynamic>) {
			return const [];
		}

		final daysRaw = data['days'];
		if (daysRaw is! List) return const [];

		final result = <_PlannerDailyIngredients>[];
		for (final day in daysRaw) {
			if (day is! Map<String, dynamic>) continue;
			final date = DateTime.tryParse((day['date'] ?? '').toString());
			if (date == null) continue;

			final ingredientsRaw = day['ingredients'];
			final ingredients = <_PlannerIngredientRow>[];
			if (ingredientsRaw is List) {
				for (final ing in ingredientsRaw) {
					if (ing is! Map<String, dynamic>) continue;
					final name = (ing['name'] ?? '').toString().trim();
					if (name.isEmpty) continue;
					final quantity = ing['quantity'] is num
						? (ing['quantity'] as num).toDouble()
						: double.tryParse((ing['quantity'] ?? '').toString()) ?? 1;
					final unit = (ing['unit'] ?? '').toString().trim();
					ingredients.add(
						_PlannerIngredientRow(
							name: name,
							quantity: quantity <= 0 ? 1 : quantity,
							unit: unit,
						),
					);
				}
			}

			result.add(
				_PlannerDailyIngredients(
					date: normalizeDate(date.toLocal()),
					ingredients: ingredients,
				),
			);
		}

		return result;
	}

	String _formatDate(DateTime date) {
		final normalized = normalizeDate(date);
		return '${normalized.day.toString().padLeft(2, '0')}/${normalized.month.toString().padLeft(2, '0')}/${normalized.year}';
	}

	String _formatLegacyDate(DateTime date) {
		final normalized = normalizeDate(date);
		return '${normalized.day.toString().padLeft(2, '0')}/${normalized.month.toString().padLeft(2, '0')}';
	}

	String _formatWeekLabel(DateTime weekStart) {
		final start = normalizeDate(weekStart);
		final end = start.add(const Duration(days: 6));
		return '${_formatDate(start)}-${_formatDate(end)}';
	}
}